-- MySQL Script generated by MySQL Workbench
-- Wed Oct 15 13:41:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema planning
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `planning` ;

-- -----------------------------------------------------
-- Schema planning
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `planning` ;
USE `planning` ;

-- -----------------------------------------------------
-- Table `planning`.`klas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `planning`.`klas` ;

CREATE TABLE IF NOT EXISTS `planning`.`klas` (
  `idklas` INT(11) NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idklas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planning`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `planning`.`user` ;

CREATE TABLE IF NOT EXISTS `planning`.`user` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `wachtwoord` VARCHAR(255) NOT NULL,
  `rol` TINYINT(4) NOT NULL,
  `idklas` INT(11) NOT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `fk_user_klas1_idx` (`idklas` ASC) VISIBLE,
  CONSTRAINT `fk_user_klas1`
    FOREIGN KEY (`idklas`)
    REFERENCES `planning`.`klas` (`idklas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planning`.`vak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `planning`.`vak` ;

CREATE TABLE IF NOT EXISTS `planning`.`vak` (
  `idvak` INT(11) NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvak`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planning`.`Taak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `planning`.`Taak` ;

CREATE TABLE IF NOT EXISTS `planning`.`Taak` (
  `idtaak` INT(11) NOT NULL AUTO_INCREMENT,
  `bereikt` VARCHAR(45) NOT NULL,
  `doel` VARCHAR(45) NOT NULL,
  `drempel` VARCHAR(45) NOT NULL,
  `iduser` INT(11) NOT NULL,
  `idvak` INT(11) NOT NULL,
  PRIMARY KEY (`idtaak`),
  INDEX `fk_Taak_user_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_Taak_vak1_idx` (`idvak` ASC) VISIBLE,
  CONSTRAINT `fk_Taak_user`
    FOREIGN KEY (`iduser`)
    REFERENCES `planning`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Taak_vak1`
    FOREIGN KEY (`idvak`)
    REFERENCES `planning`.`vak` (`idvak`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
